const courses = [
  { name: "Thermal Oxidizers" },
  { name: "User Acceptance Testing" },
  { name: "Public Administration" },
  { name: "Microsoft MVP" },
  { name: "CPI" },
  { name: "Xeriscaping" },
  { name: "NCFM Certified" },
  { name: "RMS" },
  { name: "Real Estate Financing" },
  { name: "MBCI" },
  { name: "French" },
  { name: "IEX" },
  { name: "Ergonomics" },
  { name: "CBRN" },
  { name: "Oil Painting" },
  { name: "ERP" },
  { name: "Clinical Development" },
  { name: "Outcomes Research" },
  { name: "Human Factors" },
  { name: "HR Metrics" },
  { name: "VPLS" },
  { name: "Change Management" },
  { name: "Digital TV" },
  { name: "IBS" },
  { name: "Reverse Osmosis" },
  { name: "HV" },
  { name: "MS VC++" },
  { name: "Telephone Skills" },
  { name: "Kickstart" },
  { name: "Aquatic Ecology" },
  { name: "Occupational Therapy" },
  { name: "Rheology" },
  { name: "Service Delivery" },
  { name: "Thermodynamics" },
  { name: "IGOR Pro" },
  { name: "Architectural Design" },
  { name: "FFA" },
  { name: "Jetty" },
  { name: "Dysarthria" },
  { name: "gSOAP" },
  { name: "ABAP" },
  { name: "MCSD" },
  { name: "Radiology" },
  { name: "Hedge Funds" },
  { name: "JNCIP" },
  { name: "Current Affairs" },
  { name: "Business Process" },
  { name: "Engineering" },
  { name: "MRPII" },
  { name: "CCS" },
  { name: "Vi" },
  { name: "jQTouch" },
  { name: "VMware vCenter" },
  { name: "Lymphoma" },
  { name: "Nokia Qt" },
  { name: "Leases" },
  { name: "Heavy Oil" },
  { name: "IBS" },
  { name: "Fly Tying" },
  { name: "SFTP" },
  { name: "SAP-SD" },
  { name: "Tortoise CVS" },
  { name: "Silverlight" },
  { name: "PLC Allen Bradley" },
  { name: "Affiliate Networks" },
  { name: "Eye Tracking" },
  { name: "Ocular Disease" },
  { name: "HVAC Design" },
  { name: "DDTS" },
  { name: "JTIDS" },
  { name: "Twitter API" },
  { name: "GML" },
  { name: "American Welding Society (AWS)" },
  { name: "JCT" },
  { name: "Reaction Kinetics" },
  { name: "Occupational Rehabilitation" },
  { name: "Oracle OLAP" },
  { name: "PK" },
  { name: "Food Preparation" },
  { name: "Unity3D" },
  { name: "NPIV" },
  { name: "Music Production" },
  { name: "NYISO" },
  { name: "PCR Primer Design" },
  { name: "JES2" },
  { name: "Billing Systems" },
  { name: "Thermal Oxidation" },
  { name: "Ethernet over Copper" },
  { name: "Rx" },
  { name: "JDF" },
  { name: "IP PBX" },
  { name: "VLC" },
  { name: "MSA" },
  { name: "Career Counseling" },
  { name: "PTW" },
  { name: "Raw Materials" },
  { name: "TDMoIP" },
  { name: "Legal Liability" },
  { name: "JSLint" },
  { name: "Project Engineering" },
];

module.exports = { courses };
